services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=maxlord
      - MONGO_INITDB_ROOT_PASSWORD=iamblessed

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=maxlord
      - ME_CONFIG_MONGODB_ADMINPASSWORD=iamblessed
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: