server:
  port: 8020
spring:
  cloud:
    gateway:
      routes:
        - id: personal-details-service
          uri: lb:http://PERSONAL-DETAILS-SERVICE
          predicates:
            - Path=/api/v1/personal-details/**
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true


logging:
  level:
    org.springframework.cloud.gateway: info
